// nintendo3ds_main.cpp
//
// Phase 10 — Nintendo 3DS entry point. Ties together SwfLoader,
// CharacterDictionary, MovieClipInstance/ScriptEnvironment, SceneRenderer,
// Nintendo3DSRenderer, Nintendo3DSInput, and Nintendo3DSAudioBackend into a
// runnable app loop on real 3DS hardware (or a compatible emulator).
//
// Scope (documented, not silently narrowed): this phase plays back a single
// EMBEDDED demo movie (src/platform/EmbeddedDemoSwf.h) rather than loading
// an SWF from the SD card. Real file loading needs either direct FSUSER
// calls or restoring libctru's archive_dev.c (excluded from this from-
// source toolchain build over an unrelated sys/iosupport.h dependency —
// see docs/3ds-toolchain.md) to wire up open()/read() against the SD
// filesystem; that's a well-scoped, explicitly deferred follow-up, not a
// blocker for validating the rest of the Phase 10 stack end-to-end.
//
// This file is only compiled for the 3DS target (guarded by __3DS__).

#ifndef __3DS__
#error "nintendo3ds_main.cpp is only valid in a 3DS cross-compile (__3DS__ not defined)"
#endif

#include <3ds.h>

#include <algorithm>
#include <cmath>
#include <cstdio>

#include "audio/Nintendo3DSAudioBackend.h"
#include "platform/EmbeddedDemoSwf.h"
#include "platform/Log.h"
#include "platform/Nintendo3DSInput.h"
#include "renderer/Nintendo3DSRenderer.h"
#include "renderer/SceneRenderer.h"
#include "runtime/CharacterDictionary.h"
#include "runtime/MovieClipInstance.h"
#include "swf/SwfLoader.h"

using flash3ds::Log;
using flash3ds::LogLevel;
using flash3ds::audio::Nintendo3DSAudioBackend;
using flash3ds::platform::Nintendo3DSInput;
using flash3ds::renderer::Nintendo3DSRenderer;
using flash3ds::renderer::SceneRenderer;
using flash3ds::runtime::CharacterDictionary;
using flash3ds::runtime::MovieClipInstance;
using flash3ds::runtime::ScriptEnvironment;
using flash3ds::swf::SwfLoader;

int main(int argc, char** argv) {
    (void)argc;
    (void)argv;

    // NOTE: no consoleInit()/consoleDebugInit() call here -- libctru's
    // console.c is one of the files this from-source toolchain build
    // deliberately excludes (it transitively needs sys/iosupport.h's full
    // device-table framework, which isn't available with a stock, non-
    // devkitARM-patched newlib -- see docs/3ds-toolchain.md). This app has
    // no text-console output on real hardware; [3DS]-category LOG_* calls
    // still work (Log's default sink is stderr, which is harmless -- just
    // unobserved -- with no console wired up).
    gfxInitDefault();

    // Top screen: 400x240 logical pixels (standard 3DS top-screen
    // resolution; the wide/800px mode is not used here).
    constexpr int kScreenWidth = 400;
    constexpr int kScreenHeight = 240;

    auto movie = SwfLoader::loadSwf(flash3ds::platform::kEmbeddedDemoSwf,
                                     flash3ds::platform::kEmbeddedDemoSwfSize);
    // The embedded demo is generated by tools/gen_3ds_demo_swf.py and
    // independently verified (byte-for-byte, via the desktop flash_runtime
    // CLI's --render, before being committed -- see docs/3ds-toolchain.md)
    // to load and parse successfully, so a failure here means the embed
    // itself is corrupt, not a runtime-content issue. Treat it as fatal
    // rather than threading a "maybe there's no movie" case through every
    // object below (CharacterDictionary/ScriptEnvironment/MovieClipInstance/
    // SceneRenderer all assume a valid Movie that outlives them, same as
    // the desktop CLI's own main() does -- see tools/flash_runtime/main.cpp).
    if (!movie || !movie->valid) {
        LOG_ERROR("3DS", "Embedded demo movie failed to load/parse -- this is a build-time bug, "
                          "not a content issue (see EmbeddedDemoSwf.h)");
        gfxExit();
        return 1;
    }

    CharacterDictionary characters = CharacterDictionary::build(*movie);
    ScriptEnvironment env;

    Nintendo3DSAudioBackend audioBackend;
    env.setAudioBackend(&audioBackend);

    Nintendo3DSInput input(kScreenWidth, kScreenHeight);

    auto root = MovieClipInstance::createRoot(*movie, characters, env);
    if (!root) {
        LOG_ERROR("3DS", "Embedded demo movie parsed but produced no root MovieClip (no frames?)");
        gfxExit();
        return 1;
    }

    Nintendo3DSRenderer renderer(kScreenWidth, kScreenHeight, GFX_TOP);
    SceneRenderer scene(*movie, characters);

    // Frame-rate pacing: the embedded demo declares 12fps; advance the
    // movie's own timeline at that rate regardless of the 3DS's ~60Hz
    // vblank, so playback speed matches what the SWF actually specifies
    // rather than running 5x too fast. gspWaitForVBlank() is still called
    // every iteration (throttles the render/input loop to vsync, avoiding
    // a busy-spin), it just doesn't always advance the movie frame.
    const double swfFrameRate = movie->frameRateFps() > 0.0 ? movie->frameRateFps() : 12.0;
    constexpr double kVBlankHz = 60.0;
    int vblanksPerSwfFrame = std::max(1, static_cast<int>(std::lround(kVBlankHz / swfFrameRate)));
    int vblankCounter = 0;

    while (aptMainLoop()) {
        hidScanInput();
        input.poll(env.inputState());

        u32 kDown = hidKeysDown();
        if (kDown & KEY_START) {
            break;  // matches the smoke-test convention (docs/3ds-toolchain.md)
        }

        if (++vblankCounter >= vblanksPerSwfFrame) {
            vblankCounter = 0;
            root->advanceFrame();
        }

        scene.render(*root, renderer, kScreenWidth, kScreenHeight);
        gspWaitForVBlank();
    }

    audioBackend.stopAllSounds();
    gfxExit();
    return 0;
}
